var restaurantData = [
'Papillon',
'Flaming House Restaurant & Bar',
'Ocean Bar',
'Jack’s Restaurant & Bar',
'Lokanta Grill & Bar',
'Eden Silk Road Cuisine',
'Aria Korean Street Food',
'Manna',
'Lucky Pig',
'Purple Rice',
'Cocobang',
'Odagada',
'Go Go 7',
'So Gong Dong Tofu House',
'Dong Baek Restaurant',
'Banh Mi Zon',
'Pottastic',
'Din Ding Dumpling House',
'Thai BBQ',
'Vons Chicken',
'Ramen Shu',
'Bar Bay Grill',
'Tomatina',
'Round Table Pizza',
'Pho Nation',
'Tadamasa',
'Chaplin’s Sports Bistro',
'Ambrose Butchery',
'Mioki Sushi',
'Mexico Tipico',
'Fish Day',
'Tomi Sushi & Seafood Buffet',
'Ping’s Bistro',
'Tasty Pot',
'Raley’s',
'Papillon',
'Mai’s Kitchen',
'Datang Kitchen',
'Kiseki Sushi',
'Playt',
'Noodle Home',
'Federicos Grill',
'TGI Fridays',
'Tacos Papo',
'Le Petit Souffle',
'Izakaya Kikufuji',
'Heat - Edsa Shangri-La',
'Ooma',
'Sambo Kojin',
'Din Tai Fung',
'Buffet 101',
'Vikings',
'Spiral - Sofitel Philippine Plaza Manila',
'Locavore',
'Silantro Fil-Mex',
'Mad Marks Creamery & Good Eats',
'Silantro Fil-Mex',
'Guevarras',
'Sodam Korean Restaurant',
'Cafe Arabelle',
'Nonnas Pasta & Pizzeria',
'Balay Dako',
'Hobing Korean Dessert Cafe',
'Wildflour Cafe + Bakery',
'NIU by Vikings',
'The Food Hall by Todd English',
'Chez Michou',
'Cafн© Daniel Briand',
'Casa do Biscoito Mineiro',
'Maori',
'Pizza нж Bessa',
'Sushi Loko',
'Beirute',
'New Koto',
'Sandubas Cafн©',
'Villa Tevere',
'Rovereto',
'Buena Carne',
'Taco Pep',
'Coco Bambu',
'Taypнз',
'Outback Steakhouse',
'Manzuнз',
'Coco Bambu',
'Gero',
'Brazilian American Burgers',
'Pesqueiro Eco Gourmet',
'Confeitaria Colombo',
'Bibi',
'Cervantes',
'Amir',
'TT Burger',
'Braseiro da Gнзvea',
'Balada Mix',
'Garota de Ipanema',
'Zazнз BistrнЗ Tropical',
'Filн© de Ouro',
'D.O.C Ristorante',
'Sushi Leblon'
];


exports.restaurantData=restaurantData; 